feat: implement discord messages
i0bs/retux pull request #11
Opened 2022-07-21 20:30 UTC by Dworv

This PR introduces messages from Discord.

2022-07-21 20:33 UTC, EdVraz requested changes
![IMG_20220721_223306.jpg](https://user-images.githubusercontent.com/88881326/180310011-1aff2961-20c9-49cd-a660-7f0a9b6a8c0d.jpg)

2022-07-21 21:07 UTC, Dworv commented
> ![IMG_20220721_223306.jpg](https://user-images.githubusercontent.com/88881326/180310011-1aff2961-20c9-49cd-a660-7f0a9b6a8c0d.jpg)



> ![IMG_20220721_223306.jpg](https://user-images.githubusercontent.com/88881326/180310011-1aff2961-20c9-49cd-a660-7f0a9b6a8c0d.jpg)

Fixed.

2022-07-21 21:18 UTC, i0bs requested changes
This is my first batch of requested changes. The imports have been changed to be relative, and numerous typos.

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +from retux.client.resources.application import Application
```suggestion
from .application import Application
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +from retux.utils.converters import optional_c, list_c
```suggestion
from ...utils.converters import optional_c, list_c
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    "Embed",
Please add the embed proxies here

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    message_id: str | Snowflake | None = field(converter=optional_c(Snowflake), defualt=None)
```suggestion
    message_id: str | Snowflake | None = field(converter=optional_c(Snowflake), default=None)
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    channel_id: str | Snowflake | None = field(converter=optional_c(Snowflake), defualt=None)
```suggestion
    channel_id: str | Snowflake | None = field(converter=optional_c(Snowflake), default=None)
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    guild_id: str | Snowflake | None = field(converter=optional_c(Snowflake), defualt=None)
```suggestion
    guild_id: str | Snowflake | None = field(converter=optional_c(Snowflake), default=None)
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    fail_if_not_exists: bool | None = field(default=True)
```suggestion
    fail_if_not_exists: bool = field(default=True)
```
The `None` field can be removed since we're setting a default of the boolean.

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    id : `Snowflake`
```suggestion
    id : `Snowflake`, optional
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The url of the author."""
```suggestion
    """The URL of the author."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The url of author's icon."""
```suggestion
    """The URL of author's icon."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The proxied url of the author's icon."""
```suggestion
    """The proxied URL of the author's icon."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +        The url of the author.
```suggestion
        The URL of the author.
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +        The url of author's icon.
```suggestion
        The URL of author's icon.
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +        The proxied url of the author's icon.
```suggestion
        The proxied URL of the author's icon.
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +        The url of the footer icon.
```suggestion
        The URL of the footer icon.
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    The url of the footer icon.
```suggestion
    The URL of the footer icon.
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +        A proxied url of the footer icon.
```suggestion
        A proxied URL of the footer icon.
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """A proxied url of the footer icon."""
```suggestion
    """A proxied URL of the footer icon."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The components on a message."""
```suggestion
    """# The components on a message."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The message's interaction if it is a response to an interaction."""
```suggestion
    """# The message's interaction if it is a response to an interaction."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The thread of the message, if it is the message that started a thread."""
```suggestion
    """# The thread of the message, if it is the message that started a thread."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The items used to begin rendering the message's stickers."""
```suggestion
    """# The items used to begin rendering the message's stickers."""
```

2022-07-21 21:18 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The stickers of a message."""
```suggestion
    """# The stickers of a message."""
```

2022-07-21 21:26 UTC, Dworv commented on retux/client/resources/channel.py
> +    "Embed",
I didn't add an embed proxy class...

2022-07-21 21:36 UTC, i0bs requested changes
More changes

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    "Embed",
`_EmbedField` and other underscored dataclasses use the proxy paradigm

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # TODO: Implement Emojis
```suggestion
    # TODO: Implement Partial Emoji object.
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # emoji: EmojiPartial = field(converter=Emoji)
```suggestion
    # emoji: PartialEmoji = field(converter=PartialEmoji)
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +        The amount of minutes after the last message was sent before Discord automatically archives the thread.
```suggestion
        The amount of minutes after the last message was sent before
        Discord automatically archives the thread.
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +        When the thread's archive status last changed, used for calculating recent activity.
```suggestion
        When the thread's archive status last changed, used for
        calculating recent activity.
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +        If a thread is locked, only users with MANAGE_THREADS permissions can unarchive it.
```suggestion
        If a thread is locked, only users with MANAGE_THREADS permissions
        can unarchive it.
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The amount of minutes after the last message was sent before Discord automatically archives the thread."""
```suggestion
    """
    The amount of minutes after the last message was sent before
    Discord automatically archives the thread.
    """
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # TODO: Implement roles
```suggestion
    # TODO: Implement Role object.
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # TODO: Implement attachments
```suggestion
    # TODO: Implement Attachment object
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # attachments: list[dict] | list[Role] = field(converter=list_c(Attachment))
```suggestion
    # attachments: list[dict] | list[Attachment] = field(converter=list_c(Attachment))
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    """The attachments of the message."""
```suggestion
    # """The attachments of the message."""
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # TODO: Implement interactions
```suggestion
    # TODO: Implement Interaction object.
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    thread: dict | ThreadChannel | None = field(converter=optional_c(Channel), default=None)
```suggestion
    thread: dict | ThreadChannel | None = field(converter=optional_c(ThreadChannel), default=None)
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # TODO: Implement components
```suggestion
    # TODO: Implement Component object.
```

2022-07-21 21:36 UTC, i0bs commented on retux/client/resources/channel.py
> +    # TODO: Implement stickers
```suggestion
    # TODO: Implement StickerItem object.
```

2022-07-21 21:36 UTC, Dworv commented on retux/client/resources/channel.py
> +    "Embed",
Oh sure I'll do that

2022-07-21 22:00 UTC, Dworv commented
I can't find the last review. Where is it? It says there's still one left.

2022-07-22 00:11 UTC, i0bs requested changes

2022-07-22 00:11 UTC, i0bs commented on retux/client/resources/channel.py
>  from retux.client.resources.user import User
```suggestion
from .user import User
```

2022-07-22 00:11 UTC, i0bs approved these changes
LGTM, thank you for contributing to retux!

2022-07-22 00:11 UTC, merged