feat: implement discord guilds
i0bs/retux pull request #15
Opened 2022-07-27 18:59 UTC by Dworv

This PR implements the `Emoji` object into the library.

2022-07-27 19:00 UTC, Dworv commented
#14

2022-07-29 01:45 UTC, i0bs requested changes

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +@define(kwargs_only=False)
```suggestion
@define()
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +class Emoji(Object):
What's the reasoning behind making it an object subclass?

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +        Only availible on guild created emojis.
```suggestion
        Only available on guild created emojis.
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +    Only availible on guild created emojis.
```suggestion
    Only available on guild created emojis.
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +    roles : `list[Role]`, optional
```suggestion
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +        A list of roles allowed to use this emoji.
```suggestion
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +    availible : `bool`, optional
```suggestion
    available : `bool`
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +        Whether or not the emoji is availible.
```suggestion
        Whether or not the emoji is available.
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +        This may be false if the server that owns
```suggestion
        Defaults to `False` if the server that owns 
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +    availible: bool | None = field(default=None)
```suggestion
    available: bool = field(default=False)
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +    Whether or not the emoji is availible.
```suggestion
    Whether or not the emoji is available.
```

2022-07-29 01:45 UTC, i0bs commented on retux/client/resources/emoji.py
> +    This may be false if the server that owns
```suggestion
    Defaults to `False` if the server that owns 
```

2022-07-29 01:50 UTC, Dworv commented on retux/client/resources/emoji.py
> +class Emoji(Object):
I thought we were meant to subclass `Object` for classes with IDs

2022-07-29 04:27 UTC, i0bs approved these changes
LGTM, thank you for contributing to retux!

2022-07-29 04:27 UTC, merged