feat: implement channels and add some needed message objects
i0bs/retux pull request #5
Opened 2022-07-19 04:43 UTC by Dworv

This PR adds the `Channel` object, as well as all of its required dataclasses such as but not limited to `Overwrite` and `ChannelFlags`. It also adds some needed message objects like `MessageType` and `MessageFlags` among other things.

2022-07-19 12:01 UTC, i0bs requested changes
Please note some reviews target docstrings on attrs, please make sure they're carried over to the class docstring.

2022-07-19 12:01 UTC, i0bs commented on retux/client/resources/channel.py
> +    Thread member object for the current user if they have joined the thread
```suggestion
    The thread member representation of the user if they have joined the thread.
```

2022-07-19 12:01 UTC, i0bs commented on retux/client/resources/channel.py
> +    Computed permissions for the invoking user in the channel, including overwrites.
```suggestion
    The computed permissions for the invoking user in the channel, including any overwrites.
```

2022-07-19 16:01 UTC, i0bs requested changes
More clarity on `attrs` usage:

I found out that `converter` is not required when you're dealing with lists or dictionaries, as `attrs` will automatically try to work with these. It is only on custom-defined classes where you need this. I've reflected these changes to the main branch already for the other classes, so you don't have to worry about those.

*Additionally,* `attrs` will apparently complain if you try to convert a given `None` value, so any and every field with a default conversion needs to be checked. for any `flags` fields, my recommendation is setting them to `0` as the default.

2022-07-19 16:03 UTC, i0bs commented on retux/client/resources/channel.py
> +class Channel:
```suggestion
class Channel(Object):
```

2022-07-19 19:23 UTC, EdVraz commented on retux/client/resources/__init__.py
> +# from .channel import * # noqa
```suggestion
# from .channel import * # noqa

```
Follow PEP

2022-07-19 21:47 UTC, i0bs requested changes

2022-07-19 21:47 UTC, i0bs commented on retux/client/resources/channel.py
> +    Stops counting at 50.
```suggestion
    Stops counting at `50`.
```

2022-07-19 21:47 UTC, i0bs commented on retux/client/resources/channel.py
> +    Stops counting at 50.
```suggestion
    Stops counting at `50`.
```

2022-07-19 22:08 UTC, i0bs reviewed
Please remove the `=` documentation on `VideoQualityMode` and `ChannelType`. I will wait for this Pull Request to be flagged as ready for review before taking a final look.

2022-07-20 15:00 UTC, i0bs requested changes

2022-07-20 20:09 UTC, i0bs approved these changes
LGTM, thank you for contributing to retux!

2022-07-20 20:09 UTC, merged